apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: es-all-role
  labels:
    component: elasticsearch
    role: es-all-role
spec:
  serviceName: "es-all-role"
  selector:
    matchLabels:
      component: elasticsearch
      role: es-all-role
  replicas: 3
  template:
    metadata:
      labels:
        component: elasticsearch
        role: es-all-role
    spec:
      serviceAccount: elasticsearch-all
      containers:
      - name: es-all-role
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        image: harbor.paasdev.pccc.com/task/es:v5.5.2.27
        env:
        - name: KUBERNETES_CA_CERTIFICATE_FILE
          value: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: "CLUSTER_NAME"
          value: "myesallrole"
        - name: NODE_MASTER
          value: "true"
        - name: NODE_DATA
          value: "true"
        - name: NODE_INGEST
          value: "true"
        - name: HTTP_ENABLE
          value: "true"
        - name: DISCOVERY_SERVICE
          value: "elasticsearch-discovery-all"
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: storage-all
  volumeClaimTemplates:
  - metadata:
      name: storage-all
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
      storageClassName: fast

