apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-head-all
  labels:
    component: elasticsearch
    role: es-all-role
spec:
  type: NodePort
  selector:
    component: elasticsearch
    role: es-all-role
  ports:
  - name: http
    port: 9100
    targetPort: 9100 
    nodePort: 30101
    protocol: TCP
