apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-river-all
  labels:
    component: elasticsearch
    role: es-all-role
spec:
  type: NodePort
  selector:
    component: elasticsearch
    role: es-all-role
  ports:
  - name: http
    port: 18073
    targetPort: 18073 
    nodePort: 30174
    protocol: TCP
