apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-sql-all
  labels:
    component: elasticsearch
    role: es-all-role
spec:
  type: NodePort
  selector:
    component: elasticsearch
    role: es-all-role
  ports:
  - name: http
    port: 8080
    targetPort: 8080 
    nodePort: 30081
    protocol: TCP
