apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-all
  labels:
    component: elasticsearch
    role: es-all-role
spec:
  type: NodePort
  selector:
    component: elasticsearch
    role: es-all-role
  ports:
  - name: http
    port: 9200
    targetPort: 9200 
    nodePort: 30037
    protocol: TCP
